IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'dbo.DOCUMENTS'))
BEGIN
	CREATE TABLE [dbo].[DOCUMENTS] (
    [DOCUMENT_GUID]   NVARCHAR (32)   NOT NULL,
    [DOCUMENT_NUMBER] INT             IDENTITY (1, 1) NOT NULL,
    [FILE_TYPE]       NVARCHAR (100)  NOT NULL,
    [CREATED_DATE]    DATETIME        DEFAULT (getutcdate()) NULL,
    [TEXT_NAS_PATH]   NVARCHAR (400)  NOT NULL,
    [FILE_SIZE]       NUMERIC (34, 8) NOT NULL,
    [FAMILY_ID]       SMALLINT        NOT NULL,
    [UPLOAD_ID]       SMALLINT        NOT NULL,
    [RESOURCE_STATUS] NVARCHAR (3)    DEFAULT ('ACT') NOT NULL,
    [FOLDER_GUID]     NVARCHAR (32)   NOT NULL,
    [MODIFIED_DATE]   DATETIME        DEFAULT (getutcdate()) NULL,
    PRIMARY KEY CLUSTERED ([DOCUMENT_GUID] ASC),
    FOREIGN KEY ([FOLDER_GUID]) REFERENCES [dbo].[FOLDERS] ([FOLDER_GUID]));
END
GO