IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'dbo.FOLDERS'))
BEGIN
	CREATE TABLE [dbo].[FOLDERS] (
    [FOLDER_GUID]     NVARCHAR (32)  NOT NULL,
    [NAME]            NVARCHAR (100) NOT NULL,
    [CREATED_DATE]    DATETIME       DEFAULT (getutcdate()) NULL,
    [MODIFIED_DATE]   DATETIME       DEFAULT (getutcdate()) NULL,
    [RESOURCE_STATUS] NVARCHAR (3)   DEFAULT ('ACT') NOT NULL,
    PRIMARY KEY CLUSTERED ([FOLDER_GUID] ASC));
END
GO