IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'dbo.FIELDS'))
BEGIN
	CREATE TABLE [dbo].[FIELDS] (
    [FIELD_GUID]        NVARCHAR (32)  NOT NULL,
    [NAME]              NVARCHAR (200) NOT NULL,
    [DISPLAY_NAME]      NVARCHAR (200) NOT NULL,
    [DATA_TYPE]         NVARCHAR (20)  NOT NULL,
    [IS_MULTIPLE_VALUE] BIT            NOT NULL,
    [RESOURCE_STATUS]   NVARCHAR (3)   DEFAULT ('ACT') NOT NULL,
    [FOLDER_GUID]       NVARCHAR (32)  NOT NULL,
    [CREATED_DATE]      DATETIME       DEFAULT (getutcdate()) NULL,
    [MODIFIED_DATE]     DATETIME       DEFAULT (getutcdate()) NULL,
    PRIMARY KEY CLUSTERED ([FIELD_GUID] ASC),
    FOREIGN KEY ([FOLDER_GUID]) REFERENCES [dbo].[FOLDERS] ([FOLDER_GUID]));
END
GO