IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'dbo.DOCUMENTS'))
BEGIN
	IF EXISTS (SELECT 1 FROM sys.columns WHERE Name = N'FAMILY_ID' AND Object_ID = Object_ID(N'dbo.DOCUMENTS'))
	BEGIN
		ALTER TABLE DOCUMENTS ALTER COLUMN FAMILY_ID SMALLINT NULL
	END
END
GO